### ISSUE TITLE
The file default.vms is missing

### ISSUE THREAD

**Issue by JanX2** [sumiisan/onthefly#2]
It’s supposed to be in `../defaultSong/default.vms`, but that is outside of the project folder!

**Comment by sumiisan** [comment]
Hi Jan!

Thank you for contributing!
I'm a little surprised because this was the first pull request ever, and I wasn't really prepared for.
This repository was meant as my private repo so far, and was not quite up to date.
(I will try to keep it up to date in future)
I hope the newest version I did push few minutes ago, can be built without errors.

So, if you want to build the traumbaum iOS or traumbaum mac you will need the default.vms
which is the 'variable media structure' definition of the song 'traumbaum'. 
Additionally you will need the audio files to make it sound. 
If your are on a Mac, you can download the traumbaum app from

http://traumbaum.tumblr.com/post/57687679994/traumbaum-for-mac

and grab the data from inside the package.

If you want to build just the OnTheFly editor, you don't actually need default.vms.
Maybe you can try to exclude this file from the target.

sumiisan
